"""empty message

Revision ID: 9df6e00f4a63
Revises: None
Create Date: 2016-12-06 15:31:33.387759

"""

# revision identifiers, used by Alembic.
revision = '9df6e00f4a63'
down_revision = None

from alembic import op, context
from flask import current_app
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.String(), nullable=False),
    sa.Column('organisation_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organisation_id')
    )
    # ### end Alembic commands ###

    # MANUALLY ADDED the line below to grant permissions for the user found in config variable
    # APP_SQL_USERNAME on table organisation.
    context.execute(
        "GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE organisation TO " + current_app.config.get('APP_SQL_USERNAME'))
    context.execute(
        "GRANT USAGE, SELECT ON SEQUENCE organisation_id_seq TO " + current_app.config.get('APP_SQL_USERNAME'))
    ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organisation')
    # ### end Alembic commands ###
